### ISSUE TITLE
How to enable on Slackware?

### ISSUE THREAD

**Issue by drgibbon** [philipvdh/slackware-grub2-theme#1]
How should this theme be enabled on Slackware? I added `GRUB_THEME="/boot/grub/themes/slackware/theme.txt"` into `/etc/default/grub` and re-ran `grub-mkconfig` but it doesn't seem to work. Any clues?

**Comment by philipvdh** [comment]
Hi,

Do you have gfxmode enabled? 
Something like: GRUB_GFXMODE=1920x1080x32 or GRUB_GFXMODE=auto 

If that doesn't work can you send me the grub.conf that has been
generated by grub-mkconfig 

Philip

On 2019-02-22 06:37, drgibbon wrote:

> How should this theme be enabled on Slackware? I added GRUB_THEME="/boot/grub/themes/slackware/theme.txt" into /etc/default/grub and re-ran grub-mkconfig but it doesn't seem to work. Any clues? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/philipvdh/slackware-grub2-theme/issues/1
[2]

**Comment by drgibbon** [comment]
I tried with GFXMODE enabled, but no go. No problem, it might be something specific to my hardware.
